name: Slack

on: 
  workflow_run:
    workflows: [Rust]
    types: [completed]

jobs:
  slackNotification:
    name: Slack Notification
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v3
    - name: Slack Notification
      uses: rtCamp/action-slack-notify@v2
      env:
        SLACK_CHANNEL: tool-ci
        SLACK_COLOR: ${{ job.status }} # or a specific color like 'good' or '#ff00ff'
        SLACK_MESSAGE: 'Workflow id: <https://github.com/${{ github.repository }}/actions/runs/${{ github.event.workflow_run.id }}|*${{ github.event.workflow_run.id }}*>, name: *${{ github.event.workflow_run.name }}*, repo: *${{ github.repository }}*. Content :rocket:'
        SLACK_TITLE: 'Workflow outcome: *${{ github.event.workflow_run.conclusion }}*'
        SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
